# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
from ..core.serialization import FieldMetadata
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Model(UniversalBaseModel):
    first_property: typing_extensions.Annotated[
        bool, FieldMetadata(alias="firstProperty")
    ]
    second_property: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="secondProperty")
    ] = None
    third_property: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="thirdProperty")
    ] = None
    fourth_property: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="fourthProperty")
    ] = None
    fifth_property: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="fifthProperty")
    ] = None
    sixth_property: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="sixthProperty")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
