"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .model import Model, ModelTypedDict
from openapi.types import BaseModel
from openapi.utils import (
    FieldMetadata,
    HeaderMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
import pydantic
from typing_extensions import Annotated, TypedDict


class SendFormRequestTypedDict(TypedDict):
    query_param: ModelTypedDict
    header_param: ModelTypedDict
    model: ModelTypedDict


class SendFormRequest(BaseModel):
    query_param: Annotated[
        Model,
        pydantic.Field(alias="queryParam"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]

    header_param: Annotated[
        Model,
        pydantic.Field(alias="headerParam"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]

    model: Annotated[
        Model,
        FieldMetadata(
            request=RequestMetadata(media_type="application/x-www-form-urlencoded")
        ),
    ]
